name: opportune_bf
description: OpporTune BF — Plateforme de recrutement du Burkina Faso
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  http: ^1.2.1
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  file_picker: ^8.1.7
  intl: ^0.19.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/google.jpg
