name: opportune_bf
description: OpporTune BF — Plateforme de recrutement du Burkina Faso
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    

  get: ^4.6.6
  http: ^1.2.1
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1
  google_sign_in: ^7.2.0
  google_fonts: ^8.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  file_picker: ^11.0.2
  intl: ^0.20.2
  url_launcher: ^6.3.2
  image_picker: ^1.2.2
  pdf: ^3.11.1
  printing: ^5.14.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  syncfusion_flutter_pdfviewer: ^33.2.10
  video_player: ^2.11.1
  chewie: ^1.10.0
  youtube_player_flutter: ^10.0.1
  photo_view: ^0.15.0
  iconly:
    path: packages/iconly
  firebase_core: ^4.10.0
  firebase_messaging: ^16.3.0
  flutter_local_notifications: ^21.0.0
  firebase_crashlytics: ^5.2.3
  web_socket_channel: ^3.0.1
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/google.jpg
    - assets/images/operators/
